#ifndef ANIMATION_SEQUENCES_H
#define ANIMATION_SEQUENCES_H

#include "Sequencer.h"

// Enum to identify which animation to generate
enum AnimationType {
    ANIMATION_SEQUENTIAL_FLICKER,
    ANIMATION_RANDOM_FLICKER,
    ANIMATION_COUNTING_UP,
    ANIMATION_WAVE_FLICKER,
    ANIMATION_TORNADO_FLICKER,
    ANIMATION_CAPACITOR_CHARGE_UP,
    ANIMATION_DIGITAL_RAIN,
    ANIMATION_WAVEFORM_COLLAPSE,
    ANIMATION_TIMELINE_SKIM,
    ANIMATION_TEMPORAL_DESYNC,
    ANIMATION_GLITCHY_JUMP_CUT,
    ANIMATION_PLASMA_WARM_UP,
    ANIMATION_TIME_WARP_STREAKS,
    ANIMATION_CHARACTER_SCANLINE,
    ANIMATION_FOCUS_IN,
    ANIMATION_CODE_BREAKER,
    ANIMATION_TEMPORAL_PARADOX,
    ANIMATION_DIGIT_CASCADE,
    ANIMATION_ELECTRIC_SURGE,
    ANIMATION_FLIP_DISC_DISPLAY,
    ANIMATION_INTERFERENCE_PATTERN,
    ANIMATION_ALL_DISPLAYS_RANDOM
};

// Main function to generate a sequence based on type
void generateAnimationSequence(AnimationType animType, SequencerTrack tracks[3]);

#endif // ANIMATION_SEQUENCES_H