#ifndef CERTS_H
#define CERTS_H

#include <pgmspace.h>

// DigiCert Global Root G2
// Valid until: 15/Jan/2038
const char rootCACertificate[] PROGMEM = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh\n" \
"MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n" \
"d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH\n" \
"MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT\n" \
"MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\n" \
"b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb29tIEcyMIIBIjANBgkqhkiG\n" \
"9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohC7glGGSGY1UD\n" \
"9KcsLOD2ePOSEs8F9ItUOTDER0e5GzimpEonbIWbVWyvijkptVEi3INJEVy+D1qg\n" \
"iTaDKcvAZ3M3aNuzs5SA+IokwLz4ZQ26/I9aMxp+o6i6Sg/qX3ws2meAke0AEXS6\n" \
"H5coRooEFwXg5dp0yadTDH2MIiA25rcNAVh3DBbUaYtrpF72m75DEx4R2fW9jQvX\n" \
"fLJVzVb+qhBi283TEV1ClvV+PT4oKBzWWHj96HMxS8IW+zHB8oi5vvvfxHDU8A3/\n" \
"DNIodwA8q3NjPQr3IvS8O8zlIm2pRlWB0hHQNcf5pC36ClLSOsz4kPAZ3AsoPRz+\n" \
"P/22a2U=\n" \
"-----END CERTIFICATE-----\n";

#endif // CERTS_H