[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit LED Backpack Library
    bblanchon/ArduinoJson
    esphome/ESPAsyncWebServer-esphome
    esphome/AsyncTCP-esphome
    tzapu/WiFiManager
    knolleary/PubSubClient
    https://github.com/schreibfaul/ESP32-audioI2S
monitor_speed = 115200
