set_destination_time:
  description: "Set the destination time display."
  fields:
    datetime:
      description: "The date and time to set."
      example: "2015-10-21 07:28:00"
      selector:
        datetime:
set_present_time:
  description: "Set the present time display."
  fields:
    datetime:
      description: "The date and time to set."
      example: "1985-10-26 01:22:00"
      selector:
        datetime:
set_last_departed_time:
  description: "Set the last departed time display."
  fields:
    datetime:
      description: "The date and time to set."
      example: "1955-11-05 06:00:00"
      selector:
        datetime:
time_travel:
  description: "Initiate a full time travel sequence to the specified destination time."
  fields:
    datetime:
      description: "The destination date and time."
      example: "2015-10-21 07:28:00"
      selector:
        datetime:
set_status_display:
  description: "Set the time circuits displays manually (advanced)."
  fields:
    destination_month:
      description: "Destination month"
      selector:
        text:
    destination_day:
      description: "Destination day"
      selector:
        text:
    destination_year:
      description: "Destination year"
      selector:
        text:
    destination_time:
      description: "Destination time"
      selector:
        text:
    present_month:
      description: "Present month"
      selector:
        text:
    present_day:
      description: "Present day"
      selector:
        text:
    present_year:
      description: "Present year"
      selector:
        text:
    present_time:
      description: "Present time"
      selector:
        text:
    last_departed_month:
      description: "Last departed month"
      selector:
        text:
    last_departed_day:
      description: "Last departed day"
      selector:
        text:
    last_departed_year:
      description: "Last departed year"
      selector:
        text:
    last_departed_time:
      description: "Last departed time"
      selector:
        text:
run_sequence:
  description: "Run a pre-defined sequence."
  fields:
    sequence:
      description: "The sequence to run."
      selector:
        text:
favorite_radio_station:
  description: "Favorite the currently playing radio station."
  target:
    entity:
      - domain: "media_player"
clear_favorite_radio_stations:
  description: "Clear all favorite radio stations."
  target:
    entity:
      - domain: "media_player"