set_status_display:
  description: "Set the time circuits displays."
  fields:
    destination_month:
      description: "Destination month"
      selector:
        text:
    destination_day:
      description: "Destination day"
      selector:
        text:
    destination_year:
      description: "Destination year"
      selector:
        text:
    destination_time:
      description: "Destination time"
      selector:
        text:
    present_month:
      description: "Present month"
      selector:
        text:
    present_day:
      description: "Present day"
      selector:
        text:
    present_year:
      description: "Present year"
      selector:
        text:
    present_time:
      description: "Present time"
      selector:
        text:
    last_departed_month:
      description: "Last departed month"
      selector:
        text:
    last_departed_day:
      description: "Last departed day"
      selector:
        text:
    last_departed_year:
      description: "Last departed year"
      selector:
        text:
    last_departed_time:
      description: "Last departed time"
      selector:
        text:
run_sequence:
  description: "Run a pre-defined sequence."
  fields:
    sequence:
      description: "The sequence to run."
      selector:
        text:
select_sound:
  description: "Play a sound effect on the Time Circuits speaker."
  target:
    entity:
      - domain: "media_player"
  fields:
    sound:
      description: "The name of the sound effect to play."
      example: "ALARM_SOUND"
      required: true
      selector:
        select:
          options:
            - "ALARM_SOUND"
            - "ARRIVAL_THUD"
            - "CONFIRM_ON"
            - "EASTER_EGG"
            - "REBOOT_SOUND"
            - "REMINDER_ALERT"
            - "TIME_TRAVEL_FAIL"
favorite_radio_station:
  description: "Favorite the currently playing radio station."
  target:
    entity:
      - domain: "media_player"
clear_favorite_radio_stations:
  description: "Clear all favorite radio stations."
  target:
    entity:
      - domain: "media_player"