blueprint:
  name: BTTF Time Circuits - Display Home Assistant Sensor
  description: >-
    Displays the state of any Home Assistant entity on one of the display rows.
    The row will be updated whenever the script is run.
  domain: script
  input:
    mqtt_topic:
      name: MQTT Topic
      description: The MQTT topic to publish the sequencer command to.
      default: "bttf-time-circuits/cmnd/sequencer"
    target_row:
      name: Target Row
      description: The display row to show the sensor value on.
      selector:
        select:
          options:
            - label: "Top (Destination Time)"
              value: "TOP"
            - label: "Middle (Present Time)"
              value: "MIDDLE"
            - label: "Bottom (Last Time Departed)"
              value: "BOTTOM"
    entity_to_display:
      name: Entity to Display
      description: "The sensor or entity whose state you want to display (max 13 characters)."
      selector:
        entity:
    restore_row:
      name: Restore Row After a Delay
      description: "If enabled, the row will be restored to its previous state after the specified duration."
      default: false
      selector:
        boolean: {}
    duration:
      name: Display Duration (seconds)
      description: "If 'Restore Row' is enabled, how long the sensor value should remain on screen."
      default: 10
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: "s"

mode: single

sequence:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload: >
        {%- set entity_state = states(entity_to_display) -%}
        {%- set steps = [
          {
            "command": "SET_TEXT",
            "targetRow": !input target_row,
            "targetSegment": -1,
            "stringParam": entity_state
          }
        ] -%}
        {%- if restore_row -%}
          {%- set steps = steps + [
            {
              "command": "WAIT",
              "intParam": {{ (!input duration * 1000) | int }}
            },
            {
              "command": "RESTORE_ROW",
              "targetRow": !input target_row
            }
          ] -%}
        {%- endif -%}
        {{ {"tracks": [steps]} | to_json }}