blueprint:
  name: "BTTF - Dynamic Marquee Display"
  description: >-
    Display a single, scrolling line of text on one of the five data point slots.
    Use Home Assistant's templating engine to create dynamic messages, such as:
    "Outside temp is {{ states('sensor.outside_temperature') }}°C"

    This blueprint creates a script that can be called as a service from automations or other scripts.

    Note: The marquee text has a 255-character limit.
  domain: script
  input:
    target_device:
      name: Time Circuits Device
      description: Select the BTTF Time Circuits clock device.
      selector:
        device:
          manufacturer: "Doc Brown Industries"
          model: "BTTF Clock v1"
    data_point_slot:
      name: Data Point Slot
      description: "Which of the five marquee slots to use for this data. Note: The slots are numbered 1-5 in the UI for convenience, but are indexed 0-4 in the system."
      default: "1"
      selector:
        select:
          options:
            - label: "Data Point 1"
              value: "1"
            - label: "Data Point 2"
              value: "2"
            - label: "Data Point 3"
              value: "3"
            - label: "Data Point 4"
              value: "4"
            - label: "Data Point 5"
              value: "5"
    text:
      name: Marquee Text
      description: The text to display. Supports templates.
      selector:
        text: {}

variables:
  device_id: !input target_device
  # The blueprint UI uses 1-based indexing, but the entity is 0-based.
  slot: "{{ (iif(data_point_slot is string, data_point_slot | int, data_point_slot) - 1) }}"
  unique_id: "{{ device_attr(device_id, 'identifiers')[0][1] }}"

sequence:
  - service: text.set_value
    target:
      entity_id: "text.{{ unique_id }}_datapoint_{{ slot }}_marquee"
    data:
      value: !input text