blueprint:
  name: BTTF Time Circuits - Dynamic Marquee Text
  description: >-
    Display a single, scrolling line of text on the bottom display.
    You choose one of five "data slots" and provide the TEXT THAT YOU WANT TO DISPLAY.
    Use Home Assistant's templating engine to create dynamic messages.
    FOR EXAMPLE, THE TEXT COULD BE "Outside temp is {{ states('sensor.outside_temperature') }} DEGREES CELCIUS"
    THIS TEXT IS SENT BY HOME ASSISTANT USING MQTT TO THE DATA SLOT, SUBSTITUTING THE TEMPERATURE FOR {{ states('sensor.outside_temperature') }}.
    The clock's Data Point Source must be set to "Home Assistant Push" for this to work.
  domain: automation
  input:
    target_device:
      name: Time Circuits Device
      description: Select the BTTF Time Circuits clock device.
      selector:
        device:
          manufacturer: "Doc Brown Industries"
          model: "BTTF Clock v1"
    data_point_slot:
      name: Data Point Slot
      description: Which of the five marquee slots to use for this data.
      default: "0"
      selector:
        select:
          options:
            - label: "Data Point 1"
              value: "0"
            - label: "Data Point 2"
              value: "1"
            - label: "Data Point 3"
              value: "2"
            - label: "Data Point 4"
              value: "3"
            - label: "Data Point 5"
              value: "4"
    text:
      name: Marquee Text
      description: The text to display. Supports templates.
      selector:
        text:

variables:
  device_id: !input target_device
  device_name: "{{ device_attr(device_id, 'name') | lower | replace(' ', '_') }}"
  clock_id: "{{ device_attr(device_id, 'identifiers')[0][1] }}"
  slot: !input data_point_slot

# This automation has no trigger, it is meant to be called from a script or another automation.
trigger: []

action:
  - service: mqtt.publish
    data:
      topic: "timecircuits/{{ clock_id }}/datapoint/{{ slot }}/month/set"
      payload: ""
  - service: mqtt.publish
    data:
      topic: "timecircuits/{{ clock_id }}/datapoint/{{ slot }}/day/set"
      payload: ""
  - service: mqtt.publish
    data:
      topic: "timecircuits/{{ clock_id }}/datapoint/{{ slot }}/year/set"
      payload: ""
  - service: mqtt.publish
    data:
      topic: "timecircuits/{{ clock_id }}/datapoint/{{ slot }}/time/set"
      payload: "{{ text }}"