blueprint:
  name: "BTTF - Radio Streamer"
  description: >-
    Starts or stops an internet radio stream on the Time Circuits clock.
    To stop the radio, simply enter the command "stop".
  domain: automation
  input:
    time_circuits_device:
      name: Time Circuits Display
      selector:
        device:
          integration: mqtt
          manufacturer: "Doc Brown Industries"
          model: "BTTF Clock v1"
    radio_command:
      name: Radio Command
      description: The URL of the live radio stream, or "stop" to end streaming.
      selector:
        text:

variables:
  device_id: !input time_circuits_device
  unique_id: "{{ device_attr(device_id, 'identifiers')[0][1] }}"
  command: !input radio_command

action:
  - choose:
      # Condition 1: The command is "stop"
      - conditions:
          - condition: template
            value_template: "{{ command == 'stop' }}"
        sequence:
          # Stop the radio stream
          - service: mqtt.publish
            data:
              topic: "timecircuits/{{ unique_id }}/radio/command"
              payload: "stop"
          # Clear the "RADIO" text from the display
          - service: mqtt.publish
            data:
              topic: "timecircuits/{{ unique_id }}/override_text/command"
              payload: ""
          # Turn off override mode
          - service: mqtt.publish
            data:
              topic: "timecircuits/{{ unique_id }}/override/command"
              payload: "OFF"
    # Default action: The command is a URL
    default:
      # Turn on override mode to show the "RADIO" text
      - service: mqtt.publish
        data:
          topic: "timecircuits/{{ unique_id }}/override/command"
          payload: "ON"
      # Display "RADIO" on the destination month segment
      - service: mqtt.publish
        data:
          topic: "timecircuits/{{ unique_id }}/override_text/command"
          payload: "RADIO"
      # Send the radio stream URL to the clock
      - service: mqtt.publish
        data:
          topic: "timecircuits/{{ unique_id }}/radio/command"
          payload: "{{ command }}"